// Report rendering. Turns a QaAuditReport into the three shapes we deliver:
//   - Markdown  (terminal / CI logs / GitHub artifacts)
//   - HTML      (admin report view + email body)
//   - a short   plaintext/HTML email summary
//
// Pure functions, no runtime dependencies — safe everywhere.

import type { CheckResult, OverallStatus, QaAuditReport } from "./types";

const STATUS_EMOJI: Record<OverallStatus, string> = { GREEN: "🟢", YELLOW: "🟡", RED: "🔴" };
const CHECK_EMOJI: Record<CheckResult["status"], string> = { pass: "✅", warn: "⚠️", fail: "❌", skip: "⏭️" };
const STATUS_COLOR: Record<OverallStatus, string> = { GREEN: "#1a9e55", YELLOW: "#c98a1a", RED: "#d23b3b" };

function fmtWhen(iso: string): string {
  return new Date(iso).toLocaleString("en-US", { timeZone: "America/Los_Angeles", timeZoneName: "short" });
}

function groupByCategory(checks: CheckResult[]): Map<string, CheckResult[]> {
  const map = new Map<string, CheckResult[]>();
  for (const c of checks) {
    if (!map.has(c.category)) map.set(c.category, []);
    map.get(c.category)!.push(c);
  }
  return map;
}

// ---------------------------------------------------------------- Markdown ---

export function renderMarkdown(r: QaAuditReport): string {
  const lines: string[] = [];
  lines.push(`# ${STATUS_EMOJI[r.status]} AiPM QA Audit — ${r.status}`);
  lines.push("");
  lines.push(`**${r.headline}**`);
  lines.push("");
  lines.push(`- Target: \`${r.target}\``);
  lines.push(`- Environment: \`${r.environment}\`${r.version ? ` · Version \`${r.version}\`` : ""}`);
  lines.push(`- Ran: ${fmtWhen(r.startedAt)} (${(r.durationMs / 1000).toFixed(1)}s)`);
  lines.push(`- Results: ✅ ${r.counts.pass} · ⚠️ ${r.counts.warn} · ❌ ${r.counts.fail} · ⏭️ ${r.counts.skip} (of ${r.counts.total})`);
  lines.push("");

  for (const [category, checks] of Array.from(groupByCategory(r.checks).entries())) {
    lines.push(`## ${category}`);
    lines.push("");
    for (const c of checks) {
      lines.push(`- ${CHECK_EMOJI[c.status]} **${c.name}** — ${c.summary}${c.critical ? " _(critical)_" : ""}`);
      if (c.detail) lines.push(`  - ${c.detail}`);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push(`_Generated by the AiPM QA Audit. This report lists every check performed._`);
  return lines.join("\n");
}

// -------------------------------------------------------------------- HTML ---

function esc(s: string): string {
  return String(s).replace(/[&<>"]/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[ch]!));
}

export function renderHtml(r: QaAuditReport): string {
  const color = STATUS_COLOR[r.status];
  const rows = Array.from(groupByCategory(r.checks))
    .map(([category, checks]) => {
      const items = checks
        .map((c) => {
          const badgeColor = c.status === "pass" ? "#1a9e55" : c.status === "warn" ? "#c98a1a" : c.status === "fail" ? "#d23b3b" : "#6b7280";
          return `<tr>
            <td style="padding:10px 12px;border-bottom:1px solid #23252b;white-space:nowrap;">
              <span style="display:inline-block;min-width:56px;padding:2px 8px;border-radius:999px;background:${badgeColor}22;color:${badgeColor};font-weight:600;font-size:12px;text-transform:uppercase;">${c.status}</span>
            </td>
            <td style="padding:10px 12px;border-bottom:1px solid #23252b;">
              <div style="font-weight:600;color:#e8e8ea;">${esc(c.name)}${c.critical ? ' <span style="color:#d23b3b;font-size:11px;">(critical)</span>' : ""}</div>
              <div style="color:#a9adb6;font-size:13px;margin-top:2px;">${esc(c.summary)}</div>
              ${c.detail ? `<div style="color:#7f838c;font-size:12px;margin-top:2px;">${esc(c.detail)}</div>` : ""}
            </td>
            <td style="padding:10px 12px;border-bottom:1px solid #23252b;text-align:right;color:#7f838c;font-size:12px;white-space:nowrap;">${c.durationMs}ms</td>
          </tr>`;
        })
        .join("");
      return `<tr><td colspan="3" style="padding:18px 12px 6px;color:#c9a84c;font-weight:700;font-size:13px;letter-spacing:.04em;text-transform:uppercase;">${esc(category)}</td></tr>${items}`;
    })
    .join("");

  return `<!-- AiPM QA Audit report -->
<div style="max-width:920px;margin:0 auto;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;background:#0d0d0f;color:#e8e8ea;padding:24px;border-radius:12px;">
  <div style="display:flex;align-items:center;gap:14px;border-left:6px solid ${color};padding:14px 18px;background:${color}14;border-radius:8px;">
    <div style="font-size:34px;line-height:1;">${STATUS_EMOJI[r.status]}</div>
    <div>
      <div style="font-size:22px;font-weight:800;color:${color};">${r.status}</div>
      <div style="font-size:15px;color:#e8e8ea;margin-top:2px;">${esc(r.headline)}</div>
    </div>
  </div>
  <div style="display:flex;flex-wrap:wrap;gap:8px;margin:16px 0;font-size:13px;color:#a9adb6;">
    <span style="background:#17181c;padding:6px 12px;border-radius:6px;">Target: <b style="color:#e8e8ea;">${esc(r.target)}</b></span>
    <span style="background:#17181c;padding:6px 12px;border-radius:6px;">Env: <b style="color:#e8e8ea;">${esc(r.environment)}</b></span>
    ${r.version ? `<span style="background:#17181c;padding:6px 12px;border-radius:6px;">Version: <b style="color:#e8e8ea;">${esc(r.version)}</b></span>` : ""}
    <span style="background:#17181c;padding:6px 12px;border-radius:6px;">Ran: <b style="color:#e8e8ea;">${esc(fmtWhen(r.startedAt))}</b></span>
    <span style="background:#17181c;padding:6px 12px;border-radius:6px;">Took: <b style="color:#e8e8ea;">${(r.durationMs / 1000).toFixed(1)}s</b></span>
  </div>
  <div style="display:flex;gap:8px;margin-bottom:16px;">
    <div style="flex:1;text-align:center;background:#0f1f16;border:1px solid #1a9e5544;border-radius:8px;padding:10px;"><div style="font-size:22px;font-weight:800;color:#1a9e55;">${r.counts.pass}</div><div style="font-size:11px;color:#a9adb6;">PASSED</div></div>
    <div style="flex:1;text-align:center;background:#211c0f;border:1px solid #c98a1a44;border-radius:8px;padding:10px;"><div style="font-size:22px;font-weight:800;color:#c98a1a;">${r.counts.warn}</div><div style="font-size:11px;color:#a9adb6;">WARNINGS</div></div>
    <div style="flex:1;text-align:center;background:#211013;border:1px solid #d23b3b44;border-radius:8px;padding:10px;"><div style="font-size:22px;font-weight:800;color:#d23b3b;">${r.counts.fail}</div><div style="font-size:11px;color:#a9adb6;">FAILED</div></div>
    <div style="flex:1;text-align:center;background:#17181c;border:1px solid #33343a;border-radius:8px;padding:10px;"><div style="font-size:22px;font-weight:800;color:#8a8d94;">${r.counts.skip}</div><div style="font-size:11px;color:#a9adb6;">SKIPPED</div></div>
  </div>
  <table style="width:100%;border-collapse:collapse;background:#111216;border-radius:10px;overflow:hidden;">
    <tbody>${rows}</tbody>
  </table>
  <div style="margin-top:14px;color:#7f838c;font-size:12px;">Generated by the AiPM QA Audit · every check performed is listed above.</div>
</div>`;
}

/** Full standalone HTML document (for the report.html endpoint / saved artifact). */
export function renderHtmlDocument(r: QaAuditReport): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AiPM QA Audit — ${r.status}</title><style>body{margin:0;background:#0d0d0f;}</style></head><body>${renderHtml(r)}</body></html>`;
}

// ------------------------------------------------------------------- Email ---

export function renderEmailSubject(r: QaAuditReport): string {
  return `${STATUS_EMOJI[r.status]} AiPM QA Audit: ${r.status} — ${r.counts.pass}/${r.counts.total - r.counts.skip} passed (${r.environment})`;
}

export function renderEmailText(r: QaAuditReport): string {
  const problems = r.checks.filter((c) => c.status === "fail" || c.status === "warn");
  const lines = [
    `AiPM QA Audit — ${r.status}`,
    r.headline,
    "",
    `Target: ${r.target}`,
    `Environment: ${r.environment}${r.version ? ` (v${r.version})` : ""}`,
    `Ran: ${fmtWhen(r.startedAt)} in ${(r.durationMs / 1000).toFixed(1)}s`,
    `Results: ${r.counts.pass} passed, ${r.counts.warn} warnings, ${r.counts.fail} failed, ${r.counts.skip} skipped.`,
    "",
  ];
  if (problems.length === 0) {
    lines.push("All checks passed. No action needed.");
  } else {
    lines.push("Attention needed:");
    for (const c of problems) lines.push(`  ${CHECK_EMOJI[c.status]} [${c.category}] ${c.name}: ${c.summary}`);
  }
  return lines.join("\n");
}
