// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/OptionA.tsx": () => import("../components/mockups/login-variants/OptionA.tsx"),
  "./components/mockups/login-variants/OptionB.tsx": () => import("../components/mockups/login-variants/OptionB.tsx"),
  "./components/mockups/login-variants/OptionC.tsx": () => import("../components/mockups/login-variants/OptionC.tsx")
};
